version: '3'

services:

#  server:
#    image: tomcat
#    container_name: server
#    restart: always
#    ports:
#      - "8080:8080"
#    volumes:
#      - ../src:/usr/local/tomcat/webapps/

  db:
    image: mysql:5.7
    restart: always
    container_name: db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
    volumes:
      - ./databases:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    container_name: phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_VERBOSE: db
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
    links:
      - db
